"""
DFARS Desktop - SWGDE-compliant report generator.

Ported from the original DFARS Flask app. The only behavioral change
is in `save_report`: the path containment check is now against the
app-configured `reports_dir()` from `app.paths` instead of a hardcoded
`./reports` path.
"""

from __future__ import annotations

import json
import os
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from jinja2 import BaseLoader, select_autoescape
from jinja2.sandbox import SandboxedEnvironment

from .database import ForensicsDatabase
from .models import AnalysisNote, Case, Evidence
from .paths import reports_dir as default_reports_dir


DEFAULT_TEMPLATE = """---
case_id: "{{ case_id }}"
report_type: "Forensic Analysis Report"
date: "{{ date }}"
investigator: "{{ investigator }}"
agency: "{{ agency }}"
tags:
  {%- for tag in tags %}
  - "{{ tag }}"
  {%- endfor %}
status: "{{ status }}"
priority: "{{ priority }}"
classification: "{{ classification }}"
---

# {{ case_name }} - Forensic Analysis Report

## Executive Summary
> {{ executive_summary }}

## Case Overview
- **Case ID**: `{{ case_id }}`
- **Report Type**: Forensic Analysis Report
- **Date**: {{ date }}
- **Investigator**: {{ investigator }}
- **Agency**: {{ agency }}
- **Status**: {{ status }}
- **Priority**: {{ priority }}
- **Classification**: {{ classification }}

## Table of Contents
- [Case Overview](#case-overview)
- [Evidence Log](#evidence-log)
- [Analysis Findings](#analysis-findings)
- [Chain of Custody](#chain-of-custody)
- [Hash Verification](#hash-verification)
- [Tool Usage](#tool-usage)
- [Conclusion](#conclusion)
- [Appendices](#appendices)

---

## Evidence Log

| Evidence ID | Description | Collected By | Collection Date/Time | Location | Status |
|-------------|-------------|--------------|----------------------|----------|--------|
{%- for evidence in evidence_log %}
| {{ evidence.evidence_id }} | {{ evidence.description }} | {{ evidence.collected_by }} | {{ evidence.collection_datetime }} | {{ evidence.location or "" }} | {{ evidence.status }} |
{%- endfor %}

## Analysis Findings

{{ detailed_analysis }}

### Key Findings
{%- for key_finding in key_findings %}
- {{ key_finding }}
{%- endfor %}

---

## Chain of Custody

{%- for custody in chain_of_custody %}
### Custody Event {{ loop.index }}
- **Date/Time**: {{ custody.custody_datetime }}
- **Action**: {{ custody.action }}
- **From**: {{ custody.from_party }}
- **To**: {{ custody.to_party }}
- **Location**: {{ custody.location or "" }}
- **Purpose**: {{ custody.purpose or "" }}
- **Notes**: {{ custody.notes or "" }}

---
{%- endfor %}

## Hash Verification

| Evidence ID | Algorithm | Hash Value | Verified By | Verification Date |
|-------------|-----------|------------|-------------|-------------------|
{%- for hash in hash_verification %}
| {{ hash.evidence_id }} | {{ hash.algorithm }} | {{ hash.hash_value }} | {{ hash.verified_by }} | {{ hash.verification_datetime }} |
{%- endfor %}

## Tool Usage

| Tool | Version | Purpose | Command/Usage | Output File |
|------|---------|---------|---------------|-------------|
{%- for tool in tool_usage %}
| {{ tool.tool_name }} | {{ tool.version or "" }} | {{ tool.purpose }} | {{ tool.command_used or "" }} | {{ tool.output_file or "" }} |
{%- endfor %}

## Conclusion

{{ conclusion }}

## Appendices

### Appendix A: Glossary

{%- for term, definition in glossary.items() %}
- **{{ term }}**: {{ definition }}
{%- endfor %}

### Appendix B: Case Metadata

- **Total Evidence Items**: {{ evidence_count }}
- **Total Custody Events**: {{ custody_count }}
- **Total Hash Verifications**: {{ hash_count }}
- **Tools Used**: {{ tools_used|join(", ") }}
- **Analysis Notes**: {{ analysis_notes_count }}

### Appendix C: Notes

{{ notes }}

---

*Report generated by DFARS Desktop*
*System Version: 1.0.0*
*Generated: {{ generation_timestamp }}*
*Case ID: {{ case_id }}*
"""


class ForensicReportGenerator:
    """Generates forensic reports from case data using sandboxed Jinja2."""

    def __init__(self, database: ForensicsDatabase):
        self.db = database
        self.env = SandboxedEnvironment(
            loader=BaseLoader(),
            autoescape=select_autoescape(default=False, default_for_string=False),
        )

    def generate_report(self, case_id: str, format_type: str = "markdown") -> str:
        case = self.db.get_case(case_id)
        if not case:
            raise ValueError(f"Case {case_id} not found")

        evidence_list = self.db.get_evidence_for_case(case_id)

        custody_chains = []
        hash_verifications = []
        for evidence in evidence_list:
            custody_chains.extend(self.db.get_custody_chain(evidence.evidence_id))
            hash_verifications.extend(self.db.get_hash_verifications(evidence.evidence_id))

        tool_usage = self.db.get_tool_usage_for_case(case_id)
        analysis_notes = self.db.get_analysis_notes(case_id)
        tags = self.db.get_tags_for_case(case_id)
        stats = self.db.get_case_statistics(case_id)

        template_data: Dict[str, Any] = {
            "case_id": case.case_id,
            "case_name": case.case_name,
            "description": case.description,
            "investigator": case.investigator,
            "agency": case.agency,
            "start_date": case.start_date.isoformat() if case.start_date else "",
            "end_date": case.end_date.isoformat() if case.end_date else "",
            "status": case.status,
            "priority": case.priority,
            "classification": case.classification,
            "date": datetime.now().strftime("%Y-%m-%d"),
            "tags": tags,
            "evidence_log": [e.to_dict() for e in evidence_list],
            "chain_of_custody": [c.to_dict() for c in custody_chains],
            "hash_verification": [h.to_dict() for h in hash_verifications],
            "tool_usage": [t.to_dict() for t in tool_usage],
            "analysis_notes": [n.to_dict() for n in analysis_notes],
            "key_findings": [
                n.finding for n in analysis_notes if n.confidence_level in ("High", "Medium")
            ],
            "detailed_analysis": "\n\n".join(
                n.description for n in analysis_notes if n.description
            ),
            "conclusion": self._generate_conclusion(case, evidence_list, analysis_notes),
            "glossary": self._get_glossary(),
            "notes": "Report generated by DFARS Desktop",
            "evidence_count": stats["evidence_count"],
            "custody_count": stats["custody_count"],
            "hash_count": stats["hash_count"],
            "tools_used": stats["tools_used"],
            "analysis_notes_count": stats["analysis_notes_count"],
            "generation_timestamp": datetime.now().isoformat(),
            "executive_summary": self._generate_executive_summary(
                case, evidence_list, analysis_notes
            ),
        }

        template = self.env.from_string(DEFAULT_TEMPLATE)
        return template.render(**template_data)

    def generate_json_report(self, case_id: str) -> str:
        case = self.db.get_case(case_id)
        if not case:
            raise ValueError(f"Case {case_id} not found")

        evidence_list = self.db.get_evidence_for_case(case_id)
        custody_chains = []
        hash_verifications = []
        for evidence in evidence_list:
            custody_chains.extend(self.db.get_custody_chain(evidence.evidence_id))
            hash_verifications.extend(self.db.get_hash_verifications(evidence.evidence_id))

        report_data = {
            "case": case.to_dict(),
            "evidence": [e.to_dict() for e in evidence_list],
            "chain_of_custody": [c.to_dict() for c in custody_chains],
            "hash_verification": [h.to_dict() for h in hash_verifications],
            "tool_usage": [t.to_dict() for t in self.db.get_tool_usage_for_case(case_id)],
            "analysis_notes": [n.to_dict() for n in self.db.get_analysis_notes(case_id)],
            "tags": self.db.get_tags_for_case(case_id),
            "statistics": self.db.get_case_statistics(case_id),
            "generated_at": datetime.now().isoformat(),
            "report_version": "1.0.0",
        }
        return json.dumps(report_data, indent=2, default=str)

    def save_report(
        self,
        case_id: str,
        format_type: str = "markdown",
        output_dir: Optional[str | Path] = None,
    ) -> str:
        """
        Save a generated report to disk and return the absolute file path.

        Security: the output directory must be the configured reports directory
        or a subdirectory of it. Case ID is sanitized for use in the filename.
        """
        safe_case_id = re.sub(r"[^a-zA-Z0-9_\-]", "_", case_id)

        base_dir = default_reports_dir().resolve()
        resolved_dir = Path(output_dir).resolve() if output_dir else base_dir

        # Containment check: resolved_dir must be inside base_dir
        try:
            resolved_dir.relative_to(base_dir)
        except ValueError:
            raise ValueError(
                f"Output directory must be within {base_dir}, got {resolved_dir}"
            )

        resolved_dir.mkdir(parents=True, exist_ok=True)

        if format_type.lower() == "json":
            content = self.generate_json_report(case_id)
            extension = ".json"
        else:
            content = self.generate_report(case_id, format_type)
            extension = f".{format_type}"

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{safe_case_id}_forensic_report_{timestamp}{extension}"
        filepath = resolved_dir / filename

        # Final containment check on the full filepath
        try:
            filepath.resolve().relative_to(base_dir)
        except ValueError:
            raise ValueError("Path traversal detected in output path")

        filepath.write_text(content, encoding="utf-8")
        return str(filepath)

    # ─── Helpers ─────────────────────────────────────────────

    def _generate_executive_summary(
        self,
        case: Case,
        evidence_list: List[Evidence],
        analysis_notes: List[AnalysisNote],
    ) -> str:
        high_conf = [n.finding for n in analysis_notes if n.confidence_level == "High"]
        med_conf = [n.finding for n in analysis_notes if n.confidence_level == "Medium"]

        summary = f"Analysis of {len(evidence_list)} evidence items in case {case.case_id}. "
        if high_conf:
            summary += f"Key findings include: {'; '.join(high_conf[:3])}. "
        elif med_conf:
            summary += f"Notable findings include: {'; '.join(med_conf[:3])}. "
        else:
            summary += "Analysis completed; see detailed findings section. "
        summary += f"Case status: {case.status}. Priority: {case.priority}."
        return summary

    def _generate_conclusion(
        self,
        case: Case,
        evidence_list: List[Evidence],
        analysis_notes: List[AnalysisNote],
    ) -> str:
        conclusion = (
            f"The examination of case {case.case_id} involved the analysis of "
            f"{len(evidence_list)} evidence items. "
        )
        high_conf = [n for n in analysis_notes if n.confidence_level == "High"]
        med_conf = [n for n in analysis_notes if n.confidence_level == "Medium"]
        if high_conf:
            conclusion += (
                "High confidence findings: "
                f"{'; '.join(n.finding for n in high_conf)}. "
            )
        if med_conf:
            conclusion += (
                "Medium confidence findings: "
                f"{'; '.join(n.finding for n in med_conf)}. "
            )
        conclusion += (
            "All evidence was handled in accordance with SWGDE best practices for "
            "digital evidence collection, preservation, and analysis. Chain of custody "
            "was maintained throughout the examination process."
        )
        return conclusion

    @staticmethod
    def _get_glossary() -> Dict[str, str]:
        return {
            "SHA-256": "Secure Hash Algorithm 256-bit, used for verifying evidence integrity",
            "MD5": "Message Digest Algorithm 5, used for verifying evidence integrity (not recommended for security-sensitive applications)",
            "SWGDE": "Scientific Working Group on Digital Evidence",
            "NIST": "National Institute of Standards and Technology",
            "Chain of Custody": "Documented, unbroken trail of accountability that ensures the integrity of physical or digital evidence",
            "Forensic Image": "Bit-for-bit copy of digital evidence used for analysis to preserve original evidence",
            "Write Blocker": "Hardware or software tool that prevents write access to a storage device during forensic examination",
            "Timeline Analysis": "Chronological reconstruction of events based on digital evidence timestamps",
            "Artifact": "Piece of data discovered during forensic examination that may be relevant to an investigation",
        }
