"""
Embedded Ed25519 public key for verifying update manifests.

This file is BUILT INTO the .exe at PyInstaller time. The matching private
key lives in `packaging/release_private_key.pem` (gitignored) on the build
machine and signs every release manifest.

Replacing this key requires re-shipping the app — that's the whole point.
An attacker who pwns the update server still can't push a malicious
update because they don't have the private key.

# How to set this up the first time

1. Run `python packaging/keygen.py` from the project root.
   This creates `packaging/release_private_key.pem` (keep this PRIVATE)
   and prints the public key.

2. Replace `_PLACEHOLDER_PUBLIC_KEY_PEM` below with the printed public key.

3. Commit this file. NEVER commit the private key file.

4. From now on, every release you build needs to be signed with
   `packaging/sign_release.py` before you upload it.

# Placeholder behavior

While the placeholder key is still in place, the updater REFUSES to
install any update at all. This is intentional — you don't want a fresh
install pulling random updates verified against a publicly-known key.
"""

_PLACEHOLDER_PUBLIC_KEY_PEM = """\
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAREPLACETHISPUBLICKEYBEFOREBUILDINGRELEASESxxxxxxxxx=
-----END PUBLIC KEY-----
"""


# Real release-signing public key generated by packaging/keygen.py.
# The matching private key lives at packaging/release_private_key.pem
# (gitignored — DO NOT commit). Rotating this requires generating a new
# keypair and shipping a new build to every existing install.
PUBLIC_KEY_PEM: str = """\
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAb5kXj/UKxQVBzFZ8lhJ10CbCdUtL8gPwf7CjKa5yJhA=
-----END PUBLIC KEY-----
"""


def is_placeholder() -> bool:
    """True if the embedded key is still the placeholder."""
    return "REPLACETHISPUBLICKEY" in PUBLIC_KEY_PEM
