"""
Phase 6 smoke test - Ed25519 signed update manifest workflow.

Verifies:
   1. keygen.py produces a valid Ed25519 keypair
   2. sign_release.py builds a manifest, computes sha256 of a fake installer,
      and signs it with the private key
   3. Updater fetches the signed manifest from a localhost HTTP server
   4. Signature verification accepts a valid manifest
   5. Signature verification rejects a tampered manifest (one byte changed)
   6. Version comparison handles older / equal / newer / pre-release strings
   7. Updater refuses to do anything when the embedded public key is the placeholder
   8. download_update verifies sha256 and rejects on mismatch

This test temporarily monkey-patches app.update_key.PUBLIC_KEY_PEM with the
fresh public key generated by keygen.py, so the embedded-key check uses our
test key instead of the placeholder. The actual app/update_key.py file on
disk is NOT modified.

Run with: ./.venv/Scripts/python.exe docs/phase6_smoke_test.py
"""
from __future__ import annotations

import base64
import hashlib
import http.server
import json
import os
import shutil
import socket
import socketserver
import sys
import threading
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.paths import data_dir  # noqa: E402

# Clean state
dd = data_dir()
if dd.exists():
    shutil.rmtree(dd)
    print(f"Cleaned {dd}")

# Drop cached app modules so a fresh app loads
for mod in list(sys.modules):
    if mod.startswith("app"):
        sys.modules.pop(mod)

failures: list[str] = []


def fail(name: str, detail: str = ""):
    failures.append(f"{name}: {detail}" if detail else name)
    print(f"  [FAIL] {name} -- {detail}")


def ok(name: str):
    print(f"  [OK  ] {name}")


# ─── Step 1: Generate a keypair ────────────────────────────

print()
print("-- Step 1: Generate test keypair --")

from cryptography.hazmat.primitives import serialization  # noqa: E402
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey  # noqa: E402

priv = Ed25519PrivateKey.generate()
pub = priv.public_key()
priv_pem = priv.private_bytes(
    encoding=serialization.Encoding.PEM,
    format=serialization.PrivateFormat.PKCS8,
    encryption_algorithm=serialization.NoEncryption(),
)
pub_pem = pub.public_bytes(
    encoding=serialization.Encoding.PEM,
    format=serialization.PublicFormat.SubjectPublicKeyInfo,
).decode("ascii")
print(f"     private key: {len(priv_pem)} bytes")
print(f"     public key:  {len(pub_pem)} bytes")
ok("keypair generated")


# ─── Step 2: Inject the test public key into update_key ───

print()
print("-- Step 2: Inject test public key (in-memory only) --")

import app.update_key as update_key  # noqa: E402
original_pub = update_key.PUBLIC_KEY_PEM
update_key.PUBLIC_KEY_PEM = pub_pem
assert not update_key.is_placeholder()
ok("placeholder check now returns False")


# ─── Step 3: Build a fake installer + sign manifest ───────

print()
print("-- Step 3: Build a fake installer + signed manifest --")

import tempfile  # noqa: E402

fake_installer_path = Path(tempfile.gettempdir()) / "fake-DFARS-Setup-1.0.1.exe"
fake_installer_bytes = b"This is a fake installer for testing.\n" * 1000
fake_installer_path.write_bytes(fake_installer_bytes)
fake_sha = hashlib.sha256(fake_installer_bytes).hexdigest()
print(f"     fake installer: {fake_installer_path.name} "
      f"({len(fake_installer_bytes)} bytes, sha256={fake_sha[:16]}...)")

# Reach into the canonicalize helper and sign manually (mirrors sign_release.py)
from app.updater import canonical_manifest_bytes  # noqa: E402

manifest_unsigned = {
    "version": "1.0.1",
    "released_at": "2026-04-15T12:00:00+00:00",
    "channel": "stable",
    "notes": "Smoke test release",
    "windows_x64": {
        "url": "http://127.0.0.1:0/fake-installer.exe",  # patched below
        "sha256": fake_sha,
        "size_bytes": len(fake_installer_bytes),
    },
}
signature = priv.sign(canonical_manifest_bytes(manifest_unsigned))
manifest = {**manifest_unsigned, "signature": base64.b64encode(signature).decode("ascii")}
ok(f"manifest signed (sig {len(signature)} bytes)")


# ─── Step 4: Serve manifest + installer over localhost ────

print()
print("-- Step 4: Serve manifest + installer over localhost HTTP --")

# Pick a free port
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.bind(("127.0.0.1", 0))
    server_port = s.getsockname()[1]

# Patch the installer URL with the real port
manifest["windows_x64"]["url"] = f"http://127.0.0.1:{server_port}/fake-installer.exe"
# Re-sign because we mutated a signed field
signature = priv.sign(canonical_manifest_bytes(manifest))
manifest["signature"] = base64.b64encode(signature).decode("ascii")

manifest_text = json.dumps(manifest, sort_keys=True, indent=2)
print(f"     manifest size: {len(manifest_text)} bytes")


class Handler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):  # noqa: N802
        if self.path == "/manifest.json":
            body = manifest_text.encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        elif self.path == "/manifest-tampered.json":
            tampered = json.loads(manifest_text)
            tampered["version"] = "9.9.9"  # mutate after signing -> sig should fail
            body = json.dumps(tampered).encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        elif self.path == "/fake-installer.exe":
            self.send_response(200)
            self.send_header("Content-Type", "application/octet-stream")
            self.send_header("Content-Length", str(len(fake_installer_bytes)))
            self.end_headers()
            self.wfile.write(fake_installer_bytes)
        elif self.path == "/installer-corrupted.exe":
            corrupted = b"X" * len(fake_installer_bytes)
            self.send_response(200)
            self.send_header("Content-Type", "application/octet-stream")
            self.send_header("Content-Length", str(len(corrupted)))
            self.end_headers()
            self.wfile.write(corrupted)
        else:
            self.send_response(404)
            self.end_headers()

    def log_message(self, *args, **kwargs):  # silence access log
        pass


httpd = socketserver.TCPServer(("127.0.0.1", server_port), Handler)
server_thread = threading.Thread(target=httpd.serve_forever, daemon=True)
server_thread.start()
print(f"     localhost server on :{server_port}")


# ─── Step 5: check_for_update happy path ──────────────────

print()
print("-- Step 5: check_for_update (happy path) --")

# Patch DEFAULT_UPDATE_URL via config so the updater fetches our test URL
from app import config as app_config, updater  # noqa: E402

app_config.update(update_url=f"http://127.0.0.1:{server_port}/manifest.json")

try:
    info = updater.check_for_update()
    if info.version != "1.0.1":
        fail("version", f"got {info.version}")
    elif not info.is_newer:
        fail("is_newer", f"expected True (current={updater.__version__ if hasattr(updater, '__version__') else '?'})")
    elif info.sha256 != fake_sha:
        fail("sha256", f"got {info.sha256}")
    else:
        ok(f"check_for_update -> {info.version} is_newer={info.is_newer}")
except updater.UpdateError as e:
    fail("check_for_update raised", str(e))


# ─── Step 6: Tampered manifest is rejected ────────────────

print()
print("-- Step 6: Tampered manifest is rejected --")

app_config.update(update_url=f"http://127.0.0.1:{server_port}/manifest-tampered.json")
try:
    updater.check_for_update()
    fail("tampered manifest accepted", "verifier should have raised")
except updater.UpdateBadSignature:
    ok("UpdateBadSignature raised on tampered manifest")
except updater.UpdateError as e:
    fail("wrong error type for tampered manifest", f"got {type(e).__name__}: {e}")


# ─── Step 7: Version comparison edge cases ────────────────

print()
print("-- Step 7: Version comparison edge cases --")

cases = [
    ("1.0.1", "1.0.0", True),
    ("1.0.0", "1.0.0", False),
    ("1.0.0", "1.0.1", False),
    ("2.0.0", "1.99.99", True),
    ("1.0.0", "1.0.0-rc1", True),       # release beats pre-release
    ("1.0.0-rc1", "1.0.0", False),
    ("1.0.0-rc2", "1.0.0-rc1", True),   # lex on suffix
]
for cand, cur, want in cases:
    try:
        got = updater.is_newer(cand, cur)
    except Exception as e:
        fail(f"is_newer({cand!r}, {cur!r})", f"raised {e}")
        continue
    if got == want:
        ok(f"is_newer({cand!r}, {cur!r}) = {got}")
    else:
        fail(f"is_newer({cand!r}, {cur!r})", f"want {want}, got {got}")


# ─── Step 8: download_update + sha256 verification ────────

print()
print("-- Step 8: download_update verifies sha256 --")

# Reset to good manifest
app_config.update(update_url=f"http://127.0.0.1:{server_port}/manifest.json")
info = updater.check_for_update()

try:
    downloaded = updater.download_update(info)
    if downloaded.exists() and downloaded.read_bytes() == fake_installer_bytes:
        ok(f"download_update -> {downloaded.name} ({downloaded.stat().st_size} bytes)")
        downloaded.unlink(missing_ok=True)
    else:
        fail("download_update", "file missing or content mismatch")
except updater.UpdateError as e:
    fail("download_update happy path", str(e))

# Now point at a corrupted-installer URL but keep the legit sha256 in info
info.download_url = f"http://127.0.0.1:{server_port}/installer-corrupted.exe"
try:
    updater.download_update(info)
    fail("download_update accepted bad sha256", "should have raised UpdateBadHash")
except updater.UpdateBadHash:
    ok("UpdateBadHash raised on sha256 mismatch")
except updater.UpdateError as e:
    fail("wrong error type for bad sha256", f"got {type(e).__name__}: {e}")


# ─── Step 9: Placeholder key disables updates ─────────────

print()
print("-- Step 9: Placeholder key disables updates --")

update_key.PUBLIC_KEY_PEM = update_key._PLACEHOLDER_PUBLIC_KEY_PEM
assert update_key.is_placeholder()
try:
    updater.check_for_update()
    fail("placeholder key allowed update check", "should have raised UpdateDisabled")
except updater.UpdateDisabled:
    ok("UpdateDisabled raised when placeholder key is in place")
except updater.UpdateError as e:
    fail("wrong error type for placeholder", f"got {type(e).__name__}: {e}")
finally:
    update_key.PUBLIC_KEY_PEM = pub_pem  # restore for cleanup


# ─── Cleanup ───────────────────────────────────────────────

print()
print("-- Cleanup --")
httpd.shutdown()
httpd.server_close()
server_thread.join(timeout=2)
print("     local server stopped")

if fake_installer_path.exists():
    fake_installer_path.unlink()
    print("     fake installer removed")

# Restore the real (placeholder) public key
update_key.PUBLIC_KEY_PEM = original_pub


print()
if failures:
    print(f"FAILURES: {len(failures)}")
    for f in failures:
        print(f"  - {f}")
    sys.exit(1)
else:
    print("ALL TESTS PASSED")
